spring:
  datasource:
    username: root
    password: 
    url: jdbc:mysql://localhost:3306/ssm?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: cn.jack.entity
  mapper-locations: classpath:mapper/*.xml
